### ISSUE TITLE
Feature: Autocomplete GML

### ISSUE THREAD

**Issue by rszemplinski** [coppolaemilio/language-gml#2]
Thank you for the GML support in Atom! I was wondering if somehow you could get autocomplete functionality in atom so we don't have to memorize all the function names and stuff.

**Comment by coppolaemilio** [comment]
It shouldn't be so hard but unfortunately I'm not using it any more. Have you tried playing around with the code?

**Comment by coppolaemilio** [comment]
I will soon look into it :+1:

**Comment by ThomasHickman** [comment]
I have written a seperate atom package for this - https://atom.io/packages/autocomplete-gml

**Comment by coppolaemilio** [comment]
This is awesome, I'll update the read me to link to your package!
